// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAdtNfBrBWRayvaGpNk8v4U3XLGmgsOt4',
    appId: '1:876091263115:web:4adec17217ee5a09582c8e',
    messagingSenderId: '876091263115',
    projectId: 'cook-meal-f57ed',
    authDomain: 'cook-meal-f57ed.firebaseapp.com',
    storageBucket: 'cook-meal-f57ed.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAuferUoYVwhxFhQ1NbkXtC0c_rCdwV2g',
    appId: '1:876091263115:android:2a9feef7dd18425d582c8e',
    messagingSenderId: '876091263115',
    projectId: 'cook-meal-f57ed',
    storageBucket: 'cook-meal-f57ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb6HgoBJt2yVrwzznCX0Ngq_njfA9NEK0',
    appId: '1:876091263115:ios:ad217866d334e20e582c8e',
    messagingSenderId: '876091263115',
    projectId: 'cook-meal-f57ed',
    storageBucket: 'cook-meal-f57ed.firebasestorage.app',
    iosBundleId: 'com.example.cookMeal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb6HgoBJt2yVrwzznCX0Ngq_njfA9NEK0',
    appId: '1:876091263115:ios:ad217866d334e20e582c8e',
    messagingSenderId: '876091263115',
    projectId: 'cook-meal-f57ed',
    storageBucket: 'cook-meal-f57ed.firebasestorage.app',
    iosBundleId: 'com.example.cookMeal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAdtNfBrBWRayvaGpNk8v4U3XLGmgsOt4',
    appId: '1:876091263115:web:48945ebb0d67bc5a582c8e',
    messagingSenderId: '876091263115',
    projectId: 'cook-meal-f57ed',
    authDomain: 'cook-meal-f57ed.firebaseapp.com',
    storageBucket: 'cook-meal-f57ed.firebasestorage.app',
  );
}
